default:
  before_script:
    - docker info

dev deploy:
  tags:
    - dev
  script:
    - pwd
    - export DISCORD_BOT_TOKEN=$DEV_DISCORD_BOT_TOKEN
    - docker-compose build
    - docker-compose up -d
  only:
    - branches

prd deploy:
  tags:
    - prd
  script:
    - pwd
    - export DISCORD_BOT_TOKEN=$PRD_DISCORD_BOT_TOKEN
    - docker-compose build
    - docker-compose up -d
  only:
    - tags