default:
  before_script:
    - docker info

dev deploy:
  tags:
    - dev
  script:
    - cd .. && mv nijika dev-nijika && cd dev-nijika
    - export DISCORD_BOT_TOKEN=$DEV_DISCORD_BOT_TOKEN
    - docker-compose build
    - docker-compose up -d
    - cd .. && rm -rf dev-nijika
  only:
    - branches

prd deploy:
  tags:
    - prd
  script:
    - cd .. && mv nijika prd-nijika && cd prd-nijika
    - export DISCORD_BOT_TOKEN=$PRD_DISCORD_BOT_TOKEN
    - docker-compose build
    - docker-compose up -d
    - cd .. && rm -rf prd-nijika
  only:
    - tags