default:
  before_script:
    - docker info

dev deploy:
  tags:
    - dev
  script:
    - export DISCORD_BOT_TOKEN=$DEV_DISCORD_BOT_TOKEN
    - docker-compose -p dev up -d
  only:
    - branches

prd deploy:
  tags:
    - prd
  script:
    - export DISCORD_BOT_TOKEN=$PRD_DISCORD_BOT_TOKEN
    - docker-compose -p prd up -d
  only:
    - tags