default:
  before_script:
    - docker info

dev deploy:
  script:
    - export DISCORD_BOT_TOKEN="{$DEV_DISCORD_BOT_TOKEN}"
    - docker-compose build
    - docker-compose up -d

prd deploy:
  script:
    - export DISCORD_BOT_TOKEN="{$PRD_DISCORD_BOT_TOKEN}"
    - docker-compose build
    - docker-compose up -d