default:
  before_script:
    - docker info

dev deploy:
  tags:
    - dev
  script:
    - export DISCORD_BOT_TOKEN=$DEV_DISCORD_BOT_TOKEN
    - docker-compose up -p dev -d
  only:
    - branches

prd deploy:
  tags:
    - prd
  script:
    - export DISCORD_BOT_TOKEN=$PRD_DISCORD_BOT_TOKEN
    - docker-compose up -p prd -d
  only:
    - tags