default:
  before_script:
    - docker info

dev deploy:
  tags:
    - dev
  script:
    - export DISCORD_BOT_TOKEN=$DEV_DISCORD_BOT_TOKEN
    - docker-compose -p dev up -d
  only:
    - main@nev-yo-sv-gitlab-01.asaasahi.com/neverneband/nijika
  except:
    - /^release/.*$/@nev-yo-sv-gitlab-01.asaasahi.com/neverneband/nijika

prd deploy:
  tags:
    - prd
  script:
    - export DISCORD_BOT_TOKEN=$PRD_DISCORD_BOT_TOKEN
    - docker-compose -p prd up -d
  only:
    - tags