image: docker:20.10.15

services:
  - docker:20.10.15-dind

variables:
  DOCKER_DRIVER: ./
  DOCKER_TLS_CERTDIR: ""

before_script:
  - docker info

test_ci:
  script:
    - docker pull alpine:latest
    - docker run alpine:latest cat /etc/alpine-release
  tags:
    - tag-runner
